### ISSUE TITLE
initial generation fails

### ISSUE THREAD

**Issue by kuniss** [theia-ide/generator-theia-extension#27]
I'm currently working on a extension for Xtext syntax highlighting. :-)
The VS code extension works already and now thought I may try to create a Theia extension too. Unfortunately, the generator did not work for me.
 
Not sure what and why it fails. May be I'm doing something wrong.
```
denis@modula:~/VSCodeWorkspace/xtext-theia-extension$ yo theia-extension xtext-lang
XtextLang
   create package.json
   create lerna.json
identical .gitignore
   create README.md
identical .vscode/launch.json
   create xtext-lang/package.json
   create xtext-lang/tsconfig.json
   create xtext-lang/src/browser/xtext-lang-frontend-module.ts
   create xtext-lang/src/browser/xtext-lang-contribution.ts
   create browser-app/package.json
   create electron-app/package.json
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
Can you give me a hint, please?

**Comment by svenefftinge** [comment]
I think you need to instal yarn: https://yarnpkg.com/en/docs/install

**Comment by svenefftinge** [comment]
Btw, for a language extension the easiest is to copy a super simple extension and just rename it :-)
For instance the https://github.com/theia-ide/theia-ruby-extension only does the configuration and spawns a language server.

**Comment by kuniss** [comment]
The yarn installation did the trick. Thanks, @svenefftinge.
I will close it.

BTW, does Xtext already have a LS which could be used in `cd browser-example && yarn start --hostname 0.0.0.0 path/to/xtext`? Or, did I misunderstood your comment?

**Comment by svenefftinge** [comment]
It doesn't have one yet. So first step would be to go for syntax and configuration, only.
