### ISSUE TITLE
Activity Bar not available for debugger

### ISSUE THREAD

**Issue by lancemao** [theia-ide/generator-theia-extension#35]
in extension mode, some functionality in activity bar (on the very left) is missing like debugger, git, search. However, if we build the original theia repository, they are all there. Are we missing some dependency in package.json?

**Comment by vince-fugnitto** [comment]
@lancemao sorry for the late reply, are you still having issues?

**Comment by vince-fugnitto** [comment]
If I look at the `package.json` of the browser example app I can see the following dependencies:

https://github.com/theia-ide/generator-theia-extension/blob/32eb9b88a3a5003c57b8527a08a1d5f174be7281/templates/app-browser-package.json#L5-L19

Therefore extensions like `git`, `search-in-workspace`, `debug` are not there by default.
We set the minimum amount of extensions by default when generating an extension but it's up to a developer to choose what he'd like to include as part of testing his extension through the example apps.
