### ISSUE TITLE
generator broken: error TS18003: No inputs were found in config file

### ISSUE THREAD

**Issue by akashgoswami** [theia-ide/generator-theia-extension#37]
Generator fails upon running this generator with default settings. 

npm install -g yo generator-theia-extension
mkdir theia-hello-world-extension
cd theia-hello-world-extension
yo theia-extension hello-world-extension

```
hello-world-extension: $ tsc
hello-world-extension: error TS18003: No inputs were found in config file '/home/ubuntu/environment/theia-hello-world-extension/hello-world-extension/tsconfig.json'. Specified 'include' paths were '["src"]' and 'exclude' paths were '["lib"]'.
hello-world-extension: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
hello-world-extension: error Command failed with exit code 2.
hello-world-extension: npm ERR! code ELIFECYCLE
hello-world-extension: npm ERR! errno 2
hello-world-extension: npm ERR! hello-world-extension@0.0.0 prepare: `yarn run clean && yarn run build`
hello-world-extension: npm ERR! Exit status 2
hello-world-extension: npm ERR! 
hello-world-extension: npm ERR! Failed at the hello-world-extension@0.0.0 prepare script.
hello-world-extension: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
hello-world-extension: npm ERR! A complete log of this run can be found in:
hello-world-extension: npm ERR!     /home/ubuntu/.npm/_logs/2019-08-19T15_54_36_233Z-debug.log
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run prepare
lerna ERR! warning package.json: No license field
lerna ERR! warning package.json: No license field
lerna ERR! error Command failed with exit code 2.
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 2
lerna ERR! npm ERR! hello-world-extension@0.0.0 prepare: `yarn run clean && yarn run build`
lerna ERR! npm ERR! Exit status 2
lerna ERR! npm ERR! 
lerna ERR! npm ERR! Failed at the hello-world-extension@0.0.0 prepare script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR! 
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /home/ubuntu/.npm/_logs/2019-08-19T15_54_36_233Z-debug.log
lerna ERR! 
lerna ERR! 
lerna ERR! > hello-world-extension@0.0.0 prepare /home/ubuntu/environment/theia-hello-world-extension/hello-world-extension
lerna ERR! > yarn run clean && yarn run build
lerna ERR! 
lerna ERR! yarn run v1.17.3
lerna ERR! $ rimraf lib
lerna ERR! Done in 0.17s.
lerna ERR! yarn run v1.17.3
lerna ERR! $ tsc
lerna ERR! error TS18003: No inputs were found in config file '/home/ubuntu/environment/theia-hello-world-extension/hello-world-extension/tsconfig.json'. Specified 'include' paths were '["src"]' and 'exclude' paths were '["lib"]'.
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/home/ubuntu/environment/theia-hello-world-extension/node_modules/execa/index.js:236:11)
(node:16576) UnhandledPromiseRejectionWarning: Error: Command failed: npm run prepare
warning package.json: No license field
warning package.json: No license field
error Command failed with exit code 2.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! hello-world-extension@0.0.0 prepare: `yarn run clean && yarn run build`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the hello-world-extension@0.0.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-08-19T15_54_36_233Z-debug.log
```

> hello-world-extension@0.0.0 prepare /home/ubuntu/environment/theia-hello-world-extension/hello-world-extension
> yarn run clean && yarn run build

yarn run v1.17.3
$ rimraf lib
Done in 0.17s.
yarn run v1.17.3
$ tsc
error TS18003: No inputs were found in config file '/home/ubuntu/environment/theia-hello-world-extension/hello-world-extension/tsconfig.json'. Specified 'include' paths were '["src"]' and 'exclude' paths were '["lib"]'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/home/ubuntu/environment/theia-hello-world-extension/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:16576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:16576) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
`

**Comment by akashgoswami** [comment]
The file theia-hello-world-extension/hello-world-extension/tsconfig.json indeed has an src folder as input but there is no src directory as such.

**Comment by vince-fugnitto** [comment]
@akashgoswami what were the reproduction steps? you performed `yarn` on the repository?

**Comment by vince-fugnitto** [comment]
If I follow the wizard for the generation everything works correctly, example:

```
$ npm install -g yo generator-theia-extension
$ mkdir ~/a && cd ~/a
$ yo theia-extension
```

And follow the prompts for:
1. extension name
2. extension type (_hello-world_ or _widget_)

**Comment by akashgoswami** [comment]
Hi vince, 

This is weird, if I don't pass the name it works. 
If I pass the name as shown in the documentation of theia, it breaks.

Could you please confirm with passing names?

**Comment by vince-fugnitto** [comment]
> If I pass the name as shown in the documentation of theia, it breaks.

@akashgoswami do you mind sharing a link to the documentation you're referring to?

**Comment by akashgoswami** [comment]
> @akashgoswami do you mind sharing a link to the documentation you're referring to?
sorry missed that. Here it is 
https://www.theia-ide.org/doc/Authoring_Extensions.html
