### ISSUE TITLE
support extension type as an option

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/generator-theia-extension#42]
currently it is not possible to skip prompting a user because of it

**Comment by JonasHelming** [comment]
-extensionType is actually supported as a cli option (alias is -y).
`yo theia-extension -y hello-world`
creates a template without asking for the type.
I suggest to close this ticket.

**Comment by JonasHelming** [comment]
@vince-fugnitto

**Comment by vince-fugnitto** [comment]
I think we can close for now, if the issue still needs to be resolved we can re-open.
