### ISSUE TITLE
Support generating an empty extension

### ISSUE THREAD

**Issue by JonasHelming** [theia-ide/generator-theia-extension#54]
This would be useful to set up a new contribution, which is not covered by an existing template. The option to not create an example is actually already existing ("example:boolean"). However, the option is not correctly processed by most existing templates. As a consequence, if you set "example" to false, the templates will create the frontend module, but not the contribution, which leads to not compilable code. I suggest to remove the option "example" and provide a dedcaited empty template. I will push a PR.

**Comment by vince-fugnitto** [comment]
@JonasHelming I could not identify what `example` actually does. 
I attempted the following:

```
yo theia-generator --example=false
```

and selected the `hello world` option and it ultimately lead to code which successfully compiled and ran. Am I missing something?

**Comment by JonasHelming** [comment]
The hello world option handles this case correctly, try the "widget" :-)

**Comment by vince-fugnitto** [comment]
> The hello world option handles this case correctly, try the "widget" :-)

I tried using `widget` as an option and it still seemed to work?
I suspect that example is just not used as an option.

**Comment by JonasHelming** [comment]
You are right, I retested that. So you just discovered even another bug. in the "configuring" of index.ts, the "example" input parameter is not added to parameters. Therefore, in the current state, the parameter is completly ignored. If it would not be ignored, it would lead to the issue described above. So this fix addresses both issues basically by removing the example option altogether (which did not even work) and replacing this with a dedicated template.

**Comment by JonasHelming** [comment]
PR: https://github.com/theia-ide/generator-theia-extension/pull/55

**Comment by vince-fugnitto** [comment]
Closed thanks to #55
