### ISSUE TITLE
How do I create a custom editor？

### ISSUE THREAD

**Issue by Dr-Harris** [theia-ide/generator-theia-extension#67]
I want to create a custom editor through the widget example, what should I do?

**Comment by vince-fugnitto** [comment]
@Dr-Harris you can open the question directly upstream for increased visibility: https://github.com/eclipse-theia/theia/discussions
The question as it stands is rather big and involving, so if you can provide some example or use-case you are trying to achieve I think the community can help futher.

Related Questions:
- https://spectrum.chat/theia/dev/custom-editor-workflow-examples~55dae95f-fd9b-43ea-bfe1-c664c7640753
- https://spectrum.chat/theia/general/saving-of-a-custom-editor~82607477-e0f4-4f38-a5fc-16f114b0890e

_Update_:

It looks like you've already asked [here](https://github.com/eclipse-theia/theia/discussions/8105), so better to keep the discussion going.
