### ISSUE TITLE
Syntax highlighting, mini-browser not working in extension development mode

### ISSUE THREAD

**Issue by bendavis78** [theia-ide/generator-theia-extension#72]
I'm developing a new extension using `generator-theia-extension@0.1.20`. When generating the "hello" project, and running `yarn start in the browser-app directory, I noticed syntax highlighting does not work (tried on an HTML file). I also noticed I do not have access to the "Open URL" command (mini-browser).

![image](https://user-images.githubusercontent.com/324392/91669866-04a84f80-eade-11ea-96b4-cc698b7f46d7.png)

**Comment by vince-fugnitto** [comment]
@bendavis78 the necessary extensions and plugins must be added to support these features. The examples provided by the generator are simple and are meant for fast development of extensions. If you require syntax highlighting you must include the plugins which provide it (along with the plugin extensions), and mini-browser rehires `@theia/mini-browser`.
